# site description
# 网站描述
description = "Personal profile of Jeongseop Lim (임정섭), a graduate student at Korea University with research interests in programming languages and software engineering."
# date format
# 日期格式
# dateFormat = "2006-01-02"
dateFormat = "January 2, 2006"
# Home page config
# 主页信息设置
[home]
  # Home page profile
  # 主页个人信息
  [home.profile]
    # title shown in home page (HTML format is supported)
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "Jeongseop Lim (임정섭)"
    # subtitle shown in home page
    # 主页显示的网站副标题
    subtitle = ""
